# Generated by Django 6.0.2 on 2026-02-17 08:26

import django.core.validators
import django.db.models.deletion
import photos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex: Nuntă, Botez, Cununie Civilă', max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='Auto-generat din nume. Ex: nunta, botez', unique=True)),
                ('description', models.TextField(blank=True, help_text='Descriere scurtă a categoriei')),
                ('is_active', models.BooleanField(default=True, help_text='Dezactivează pentru a ascunde categoria din site')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categorie',
                'verbose_name_plural': 'Categorii',
                'db_table': 'category',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex: Andrei & Maria, Botez Sofia', max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='Auto-generat din nume. Ex: andrei-maria', unique=True)),
                ('date', models.DateField(help_text='Data evenimentului')),
                ('location', models.CharField(blank=True, help_text='Ex: București, Sala Palatului', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Descriere scurtă a evenimentului')),
                ('cover', models.ImageField(blank=True, help_text='Fotografia de copertă a albumului (max 20MB)', null=True, upload_to=photos.models.album_cover_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), photos.models.validate_image_size])),
                ('meta_title', models.CharField(blank=True, help_text='Titlu SEO (max 60 caractere). Lăsați gol pentru a folosi numele albumului.', max_length=60)),
                ('meta_description', models.CharField(blank=True, help_text='Descriere SEO (max 160 caractere)', max_length=160)),
                ('is_published', models.BooleanField(default=False, help_text='Bifați pentru a face albumul vizibil pe site')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='Ordinea de afișare în catalog (0 = primul)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='Categoria albumului', on_delete=django.db.models.deletion.PROTECT, related_name='albums', to='photos.category')),
            ],
            options={
                'verbose_name': 'Album',
                'verbose_name_plural': 'Albume',
                'db_table': 'album',
                'ordering': ['order', '-date'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Format acceptat: JPG, PNG, WebP. Max 20MB.', upload_to=photos.models.photo_upload_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), photos.models.validate_image_size])),
                ('caption', models.CharField(blank=True, help_text='Descriere scurtă a fotografiei (opțional)', max_length=255)),
                ('alt_text', models.CharField(blank=True, help_text='Text alternativ pentru accesibilitate și SEO', max_length=255)),
                ('is_featured', models.BooleanField(default=False, help_text='Marchează fotografia ca featured (afișată în preview)')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='Ordinea de afișare în album (drag & drop în admin)')),
                ('width', models.PositiveIntegerField(blank=True, editable=False, help_text='Auto-populated on upload', null=True)),
                ('height', models.PositiveIntegerField(blank=True, editable=False, help_text='Auto-populated on upload', null=True)),
                ('file_size', models.PositiveIntegerField(blank=True, editable=False, help_text='File size in bytes, auto-populated on upload', null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='photos.album')),
            ],
            options={
                'verbose_name': 'Fotografie',
                'verbose_name_plural': 'Fotografii',
                'db_table': 'photo',
                'ordering': ['order', 'uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='album',
            index=models.Index(fields=['is_published', 'category'], name='album_is_publ_085ee1_idx'),
        ),
        migrations.AddIndex(
            model_name='album',
            index=models.Index(fields=['order', '-date'], name='album_order_bc4257_idx'),
        ),
        migrations.AddIndex(
            model_name='album',
            index=models.Index(fields=['slug'], name='album_slug_c9b151_idx'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['album', 'order'], name='photo_album_i_a978c5_idx'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['is_featured'], name='photo_is_feat_00ed92_idx'),
        ),
    ]
