# Generated by Django 6.0.2 on 2026-02-24 10:32

import django.core.validators
import django.db.models.deletion
import photos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryCover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Imagine de copertă pentru categorie (max 20MB)', upload_to=photos.models.category_cover_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), photos.models.validate_image_size])),
                ('title', models.CharField(blank=True, help_text='Titlu pentru această copertă (opțional)', max_length=200)),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='Ordinea de afișare (0 = primul)')),
                ('is_active', models.BooleanField(default=True, help_text='Bifați pentru a activa această copertă')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='Categoria pentru care este această copertă', on_delete=django.db.models.deletion.CASCADE, related_name='covers', to='photos.category')),
            ],
            options={
                'verbose_name': 'Copertă Categorie',
                'verbose_name_plural': 'Coperți Categorii',
                'db_table': 'category_cover',
                'ordering': ['category', 'order', '-created_at'],
                'indexes': [models.Index(fields=['category', 'is_active', 'order'], name='category_co_categor_3eb6a4_idx')],
            },
        ),
    ]
